<div class="col" style="margin-bottom:20px;">
        <div class="card">
  <div class="card-header">
    API Usage
  </div>
  <div class="card-block">
        <h6><label class="badge badge-success">GET</label> https://headdb.com/api/head/31e712ab-7878-31ea-a398-0c86dab7b333</h6>
        <textarea readonly="" class="form-control" rows="18" onclick="this.focus();this.select()">{
    "name": "Melon",
    "uuid": "31e712ab-7878-31ea-a398-0c86dab7b333",
    "value": "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjQxNDEyYjhjNmZkNTdlNGUxNjIxNjZkZGZkNzRiMTQ4YTU5NmY5ZWIxZDE1OTNjMDQ2OTYzOGM4ZDcxNCJ9fX0=",
    "valueDecoded": {
        "textures": {
            "SKIN": {
                "url": "http://textures.minecraft.net/texture/241412b8c6fd57e4e162166ddfd74b148a596f9eb1d1593c0469638c8d714"
            }
        }
    },
    "command": "/give @p skull 1 3 {display:{Name:\"Melon\",Lore:[\"Skull from HeadDB.com\"]},SkullOwner:{Id:\"31e712ab-7878-31ea-a398-0c86dab7b333\",Properties:{textures:[{Value:\"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjQxNDEyYjhjNmZkNTdlNGUxNjIxNjZkZGZkNzRiMTQ4YTU5NmY5ZWIxZDE1OTNjMDQ2OTYzOGM4ZDcxNCJ9fX0=\"}]}}}"
}</textarea>
        <h6 style="margin-top:15px;"><label class="badge badge-success">GET</label> https://headdb.com/api/category/food</h6>
        <textarea readonly="" class="form-control" rows="20" onclick="this.focus();this.select()">{
    "31e712ab-7878-31ea-a398-0c86dab7b333": {
        "name": "Melon",
        "uuid": "31e712ab-7878-31ea-a398-0c86dab7b333",
        "value": "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjQxNDEyYjhjNmZkNTdlNGUxNjIxNjZkZGZkNzRiMTQ4YTU5NmY5ZWIxZDE1OTNjMDQ2OTYzOGM4ZDcxNCJ9fX0=",
        "valueDecoded": {
            "textures": {
                "SKIN": {
                    "url": "http://textures.minecraft.net/texture/241412b8c6fd57e4e162166ddfd74b148a596f9eb1d1593c0469638c8d714"
                }
            }
        },
        "command": "/give @p skull 1 3 {display:{Name:\"Melon\",Lore:[\"Skull from HeadDB.com\"]},SkullOwner:{Id:\"31e712ab-7878-31ea-a398-0c86dab7b333\",Properties:{textures:[{Value:\"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjQxNDEyYjhjNmZkNTdlNGUxNjIxNjZkZGZkNzRiMTQ4YTU5NmY5ZWIxZDE1OTNjMDQ2OTYzOGM4ZDcxNCJ9fX0=\"}]}}}"
    }
}</textarea>
        <h6 style="margin-top:15px;">List of category URLs</h6>
        <ul>
            <li>
                <a href="https://headdb.com/api/category/blocks">https://headdb.com/api/category/blocks</a>
            </li>
            <li>
                <a href="https://headdb.com/api/category/food">https://headdb.com/api/category/food</a>
            </li>
            <li>
                <a href="https://headdb.com/api/category/electronics">https://headdb.com/api/category/electronics</a>
            </li>
            <li>
                <a href="https://headdb.com/api/category/characters">https://headdb.com/api/category/characters</a>
            </li>
            <li>
                <a href="https://headdb.com/api/category/flags">https://headdb.com/api/category/flags</a>
            </li>
            <li>
                <a href="https://headdb.com/api/category/letters">https://headdb.com/api/category/letters</a>
            </li>
            <li>
                <a href="https://headdb.com/api/category/youtubers">https://headdb.com/api/category/youtubers</a>
            </li>
            <li>
                <a href="https://headdb.com/api/category/halloween">https://headdb.com/api/category/halloween</a>
            </li>
            <li>
                <a href="https://headdb.com/api/category/christmas">https://headdb.com/api/category/christmas</a>
            </li>
            <li>
                <a href="https://headdb.com/api/category/all">https://headdb.com/api/category/all</a>
            </li>
            <li>
                <a href="https://headdb.com/api/category/all">https://headdb.com/api/category/unverified</a>
            </li>
        </ul>
  </div>
</div>
</div>